# Generated by Django 2.0.4 on 2018-05-02 09:58

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(help_text='Нужно использовать для создания "хороших" URL-ов', max_length=200, unique=True)),
                ('available', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Заголовок новости')),
                ('slug', models.SlugField(help_text='Нужно использовать для создания "хороших" URL-ов', max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='products/img/%Y/%m/%d/', verbose_name='Картинка для новостей (300 x 300)')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание в листе')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Детальное описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('available', models.BooleanField(default=True, verbose_name='Отображать')),
                ('category', models.ForeignKey(on_delete=True, to='ru.Category', verbose_name='Категория продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
