# Generated by Django 2.0.2 on 2018-05-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.IntegerField(default='+380', max_length=13, verbose_name='Моб. телефон'),
        ),
    ]
